environment: platform_homolog_environment
### Project Settings
componentId: testesteste-12
cluster_name: testesteste-12
owner: group:default/admin
instance_type: t3.medium
volume_size: 30
keypair_name: platform_kp
### Network Settings
vpc_id: vpc-051721395ecf1f7aa
domain: vkpr.platform.vee.codes
hostedZoneId: Z08737613ML5F3HE67WJ3
subnet_id: subnet-04dda6147dd9410f1
### Ingress Settings
ingress_window: true
basic_auth: true
issuer_type: staging
email: platformss@vee.codes
### Terraform Backend Settings
terraformStateBucketName: veecode-homolog-terraform-state
terraformStateBucketRegion: us-east-1
infracost: false
### Publish Settings
host: github.com
destination: veecode-homolog/testesteste-12
specPublish: ${{ parameters.specPublish | parseRepoUrl | pick('owner') }}/${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
specPublishRepo: ${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
specPublishBranch: 
### Observability Settings
observability_window: false
## Cluster configuration 
cluster_obs_name: argocd-teste-config
cluster_obs_domain: vkpr.platform.vee.codes
cluster_obs_public_ip: 34.200.112.30